#!/bin/bash
set -ev

unset HTTP_PROXY
unset http_proxy

exec su socrata -c 'node --max_old_space_size=256 lib/index.js'
RES=$?

cp heapdump* /mnt/mesos/sandbox
cp crash.log* /mnt/mesos/sandbox

exit $RES
