#!/bin/bash
unset HTTP_PROXY
unset http_proxy


if [ -r /dev/shm/geo_import_amq.sh ]; then
  echo "Sourcing secrets to environment."
  . /dev/shm/geo_import_amq.sh
else
  echo "No secrets found in /dev/shm/geo_import_amq.sh."
fi


exec su socrata -c 'node --max_old_space_size=1024 ${ROOT_DIR}/lib/index.js'
RES=$?

cp heapdump* /mnt/mesos/sandbox
cp crash.log* /mnt/mesos/sandbox

exit $RES
